steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]

  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-app", "--build-arg=JAR_FILE=target/hello-app-1.0.0.jar", "."]

images: ["gcr.io/$PROJECT_ID/hello-app"]
